//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4thtry.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class reply
    {
        public int reply_id { get; set; }
        public int fk_reviewId { get; set; }
        public int user_id { get; set; }
        public string msg { get; set; }
        public Nullable<System.DateTime> postdate { get; set; }
    
        public virtual review review { get; set; }
        public virtual User User { get; set; }
    }
}
